# Generated by Django 5.2.8 on 2025-11-07 06:25

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('special_code', models.CharField(db_index=True, default=core.models.generate_onboarding_code, max_length=32, unique=True)),
                ('code_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.org'),
        ),
    ]
